import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'

// className change to be inter.className
const inter = Inter({ subsets: ['latin'] })

// className change to be roboto.className
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400','500']
})

// className change to be poppins.variable | poppins.className
const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
})

// tailwind: add fontFamily to tailwind.config.ts and you can use it 
// className= "font-poppins" OR we can add it in globals.css

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter|dark">
      <GoogleAnalyticsScript />
      <body className={poppins.className}>
        <AuthProvider>
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
